Repository Raviteja7Lanka/Inventory_Management_SE_Project, pull requests merged in 2022-04, with the labels that each got.

#61 Refactored the Payments API
  server/controllers/PaymentsController.go
  server/controllers/ProductsController.go
  server/controllers/StaffController.go
  server/controllers/SupplierController.go
  server/main.go
  server/models/Payments.go
  server/models/Products.go
  server/models/Staff.go
  server/models/Suppliers.go
  server/routes/payment_routes.go
  server/routes/product_routes.go
  server/routes/staff_routes.go
  server/routes/supplier_routes.go
Labels: Backend

#71 Adding handlers for main.go
  angular.json
  package-lock.json
  package.json
  server/main.go
Labels: Backend

#74 Role api to get the role_details of the staff
  server/controllers/RolesController.go
  server/models/Role.go
  server/routes/role_routes.go
Labels: Backend

#75 category routes
  server/routes/category_routes.go
Labels: Backend

#76 Updated DB for the warehouses table
  server/INVENTORY_MANAGEMENT.db
Labels: Backend, DataBase

#79 Latest angular changes
  src/app/customer-table/add-customer/add-customer.component.html
  src/app/customer-table/add-customer/add-customer.component.ts
  src/app/customer-table/customer-table.component.html
  src/app/customer-table/customer-table.component.ts
  src/app/services/api.service.ts
  src/app/supplier-table/add-supplier/add-supplier.component.html
  src/app/supplier-table/add-supplier/add-supplier.component.ts
  src/app/supplier-table/supplier-table.component.html
  src/app/supplier-table/supplier-table.component.ts
Labels: Frontend, Angular, spirnt_3

#87 API for category models
  server/models/Category.go
Labels: Backend, golang

#89 Refactored warehouse API
  server/controllers/WarehouseController.go
  server/models/Warehouses.go
  server/routes/warehouse_routes.go
Labels: Backend

#97 Unit tests for staff and suppliers API
  server/staff_test.go
  server/suppliers_test.go
Labels: Backend, Testing

#98 Surya sprint 4
  server/im.db
  server/payment_test.go
  server/products_test.go
Labels: Backend, Testing

#112 Surya sprint 4
  .github/workflows/main.yml
  .vscode/launch.json
  README.md
  angular.json
  package.json
Labels: Backend, Deployment

#113 Test
  src/app/products/products.component.css
  src/app/products/products.component.html
  src/assets/Catagory1.png
Labels: Frontend, Angular

#116 modified backend unit tests
  server/INVENTORY_MANAGEMENT.db
  server/INVENTORY_MANAGEMENT.db-journal
  server/main_test.go
  server/order_details_test.go
  server/ordersAPI_test.go
  server/products_test.go
  server/staff_test.go
  server/suppliers_test.go
  server/warehouse_test.go
  server/warehouse_test2.go
Labels: Backend, Testing
