Repository Raviteja7Lanka/Inventory_Management_SE_Project, pull requests merged in 2022-02, with the labels that each got.

#4 feat: add customer and supply table
  .browserslistrc
  .editorconfig
  .gitignore
  angular.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/customer-table/customer-table.component.css
  src/app/customer-table/customer-table.component.html
  src/app/customer-table/customer-table.component.spec.ts
  src/app/customer-table/customer-table.component.ts
  src/app/supplier-table/supplier-table.component.css
  src/app/supplier-table/supplier-table.component.html
  src/app/supplier-table/supplier-table.component.spec.ts
  src/app/supplier-table/supplier-table.component.ts
  src/app/tabs/tabs.component.css
  src/app/tabs/tabs.component.html
  src/app/tabs/tabs.component.spec.ts
  src/app/tabs/tabs.component.ts
  src/assets/.gitkeep
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/styles.css
  src/test.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
Labels: Frontend, Angular

#12 added padding and changed layout
  src/app/app.component.css
  src/app/app.component.html
  src/app/customer-table/customer-table.component.css
  src/app/customer-table/customer-table.component.html
  src/app/supplier-table/supplier-table.component.css
  src/app/tabs/tabs.component.css
  src/app/tabs/tabs.component.html
Labels: Frontend, Angular

#13 home-page created
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/my-navbar/my-navbar.component.css
  src/app/my-navbar/my-navbar.component.html
  src/app/my-navbar/my-navbar.component.spec.ts
  src/app/my-navbar/my-navbar.component.ts
  src/assets/IMG1.jpeg
  src/assets/Reports.jpeg
  src/assets/orders.png
  src/assets/service.jpeg
Labels: Frontend, Angular

#15 Landing page
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/my-navbar/my-navbar.component.html
Labels: Frontend, Angular

#18 Added Two More Button Functionalities to Supplier & Customer pages
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/customer-table/customer-table.component.css
  src/app/customer-table/customer-table.component.html
  src/app/my-navbar/my-navbar.component.html
  src/app/supplier-table/supplier-table.component.css
  src/app/supplier-table/supplier-table.component.html
Labels: Frontend, Angular

#19 Landing page
  src/app/app.component.html
Labels: bug, Angular

#20 Database Schema of the Inventory Management
  SCHEMAIVM.pdf
Labels: Backend, DataBase
